type ARECBank @entity {
  id:                     ID!
  timeTrx:                String!
  blockHeight:            String!
  numARTTokens:           Int!
  ARTTokens:              [Bytes!]!
}

type ARTToken @entity {
  id:                     ID!
  numPaymentToken:        Int!
  totalAmountDeposit:     BigInt!
  totalAmountSold:        BigInt!
  paymentTokens:          [Bytes!]!
}

type ARTTokenSale @entity {
  id:                     ID!
  salePrices:             BigInt!
  timesOfSale:            BigInt!
  saleIncomes:            BigInt!
  withdrawValues:         BigInt!
}

type Token @entity {
  id:                     ID!
  symbol:                 String!
  name:                   String!
  decimals:               BigInt!
  totalSupply:            BigInt!
}

type PlantStakeInfo @entity {
  id:                     ID!
  stakeUserCounter:       Int!
  stakeTxCounter:         Int!
  unstakeTxCounter:       Int!
  stakingMinerCounter:    Int!
  allStakeAmount:         BigInt!
  allStakeSum:            BigInt!
  allUnstakeSum:           BigInt!
  allRewardAmount:        BigInt!
}

type PlantStakeUser @entity {
  id:                     ID!
  stakeTxCounter:         Int!
  unstakeTxCounter:       Int!
  allStakeAmount:         BigInt!
  allStakeSum:            BigInt!
  allUnstakeSum:          BigInt!
  allRewardAmount:        BigInt!
}

type PlantStakeMiner @entity {
  id:                     ID!
  stakeTxCounter:         Int!
  unstakeTxCounter:       Int!
  allStakeAmount:         BigInt!
  allStakeSum:            BigInt!
  allUnstakeSum:          BigInt!
  allRewardAmount:        BigInt!
}

type PlantStakeTx @entity {
  id:                     ID!
  stakeTxSN:              Int!
  staker:                 String!
  nonce:                  Int!
  stakeType:              String!
  txid:                   String!
  cspMiner:               String!
  amount:                 BigInt!
  reward:                 BigInt!
}

type StakingRewardsInfo @entity {
  id:                     ID!
  counterTransaction:     BigInt!
  periodStart:            BigInt!
  periodEnd:              BigInt!
  totalReward:            BigInt!
  lastUpdateTime:         BigInt!
  lastBlockHeight:        BigInt!
  sumStakes:              BigInt!
  sumUntakes:             BigInt!
  sumRewards:             BigInt!
  totalStakes:            BigInt!
  totalRewardStakes:      BigInt!
  totalNormalStakes:      BigInt!
  totalBoostStakes:       BigInt!
  rewardRate:             BigInt!
  rewardPerStakeLast:     BigInt!
  capMinerBoost:          BigInt!
  rateBoost:              Int!
  minerStaked:            Int!
  MinerTxCounter:         Int!
  stakeCounter:           Int!
  unstakeCounter:         Int!
  rewardClaimCounter:     Int!
}

type StakingRewardsUser @entity {
  id:                     ID!
  lastTimeUser:           BigInt!
  lastBlockHeightUser:    BigInt!
  sumRewards:             BigInt!
  totalStakesUser:        BigInt!
  totalRewardStakesUser:  BigInt!
  totalNormalStakesUser:  BigInt!
  totalBoostStakesUser:   BigInt!
  minerStakedUser:        Int!
  MinerTxCounterUser:     Int!
  stakeCounterUser:       Int!
  unstakeCounterUser:     Int!
  rewardClaimCounter:     Int!
}

type StakeTransaction @entity {
  id:                     ID!
  user:                   String!
  type:                   String!
  timeStamp:              BigInt!
  idTransaction:          BigInt!
  amountTransaction:      BigInt!
  totalStakes:            BigInt!
  totalRewardStakes:      BigInt!
  totalNormalStakes:      BigInt!
  totalBoostStakes:       BigInt!
  minerStakedChange:      Int!
  totalStakesUser:        BigInt!
  totalRewardStakesUser:  BigInt!
  totalNormalStakesUser:  BigInt!
  totalBoostStakesUser:   BigInt!
}

type StakingRewardsInfo1 @entity {
  id:                     ID!
  counterTransaction:     BigInt!
  periodStart:            BigInt!
  periodEnd:              BigInt!
  totalReward:            BigInt!
  lastUpdateTime:         BigInt!
  lastBlockHeight:        BigInt!
  sumStakes:              BigInt!
  sumUntakes:             BigInt!
  sumRewards:             BigInt!
  totalStakes:            BigInt!
  totalRewardStakes:      BigInt!
  totalNormalStakes:      BigInt!
  totalBoostStakes:       BigInt!
  rewardRate:             BigInt!
  rewardPerStakeLast:     BigInt!
  capMinerBoost:          BigInt!
  rateBoost:              Int!
  minerStaked:            Int!
  MinerTxCounter:         Int!
  stakeCounter:           Int!
  unstakeCounter:         Int!
  rewardClaimCounter:     Int!
}

type StakingRewardsUser1 @entity {
  id:                     ID!
  lastTimeUser:           BigInt!
  lastBlockHeightUser:    BigInt!
  sumRewards:             BigInt!
  totalStakesUser:        BigInt!
  totalRewardStakesUser:  BigInt!
  totalNormalStakesUser:  BigInt!
  totalBoostStakesUser:   BigInt!
  minerStakedUser:        Int!
  MinerTxCounterUser:     Int!
  stakeCounterUser:       Int!
  unstakeCounterUser:     Int!
  rewardClaimCounter:     Int!
}

type StakeTransaction1 @entity {
  id:                     ID!
  user:                   String!
  type:                   String!
  timeStamp:              BigInt!
  idTransaction:          BigInt!
  amountTransaction:      BigInt!
  totalStakes:            BigInt!
  totalRewardStakes:      BigInt!
  totalNormalStakes:      BigInt!
  totalBoostStakes:       BigInt!
  minerStakedChange:      Int!
  totalStakesUser:        BigInt!
  totalRewardStakesUser:  BigInt!
  totalNormalStakesUser:  BigInt!
  totalBoostStakesUser:   BigInt!
}

type StakingRewardsInfo2 @entity {
  id:                     ID!
  counterTransaction:     BigInt!
  periodStart:            BigInt!
  periodEnd:              BigInt!
  totalReward:            BigInt!
  lastUpdateTime:         BigInt!
  lastBlockHeight:        BigInt!
  sumStakes:              BigInt!
  sumUntakes:             BigInt!
  sumRewards:             BigInt!
  totalStakes:            BigInt!
  totalRewardStakes:      BigInt!
  totalNormalStakes:      BigInt!
  totalBoostStakes:       BigInt!
  rewardRate:             BigInt!
  rewardPerStakeLast:     BigInt!
  capMinerBoost:          BigInt!
  rateBoost:              Int!
  minerStaked:            Int!
  MinerTxCounter:         Int!
  stakeCounter:           Int!
  unstakeCounter:         Int!
  rewardClaimCounter:     Int!
}

type StakingRewardsUser2 @entity {
  id:                     ID!
  lastTimeUser:           BigInt!
  lastBlockHeightUser:    BigInt!
  sumRewards:             BigInt!
  totalStakesUser:        BigInt!
  totalRewardStakesUser:  BigInt!
  totalNormalStakesUser:  BigInt!
  totalBoostStakesUser:   BigInt!
  minerStakedUser:        Int!
  MinerTxCounterUser:     Int!
  stakeCounterUser:       Int!
  unstakeCounterUser:     Int!
  rewardClaimCounter:     Int!
}

type StakeTransaction2 @entity {
  id:                     ID!
  user:                   String!
  type:                   String!
  timeStamp:              BigInt!
  idTransaction:          BigInt!
  amountTransaction:      BigInt!
  totalStakes:            BigInt!
  totalRewardStakes:      BigInt!
  totalNormalStakes:      BigInt!
  totalBoostStakes:       BigInt!
  minerStakedChange:      Int!
  totalStakesUser:        BigInt!
  totalRewardStakesUser:  BigInt!
  totalNormalStakesUser:  BigInt!
  totalBoostStakesUser:   BigInt!
}

type StakingRewardsInfo3 @entity {
  id:                     ID!
  counterTransaction:     BigInt!
  periodStart:            BigInt!
  periodEnd:              BigInt!
  totalReward:            BigInt!
  lastUpdateTime:         BigInt!
  lastBlockHeight:        BigInt!
  sumStakes:              BigInt!
  sumUntakes:             BigInt!
  sumRewards:             BigInt!
  totalStakes:            BigInt!
  totalRewardStakes:      BigInt!
  totalNormalStakes:      BigInt!
  totalBoostStakes:       BigInt!
  rewardRate:             BigInt!
  rewardPerStakeLast:     BigInt!
  capMinerBoost:          BigInt!
  rateBoost:              Int!
  minerStaked:            Int!
  MinerTxCounter:         Int!
  stakeCounter:           Int!
  unstakeCounter:         Int!
  rewardClaimCounter:     Int!
}

type StakingRewardsUser3 @entity {
  id:                     ID!
  lastTimeUser:           BigInt!
  lastBlockHeightUser:    BigInt!
  sumRewards:             BigInt!
  totalStakesUser:        BigInt!
  totalRewardStakesUser:  BigInt!
  totalNormalStakesUser:  BigInt!
  totalBoostStakesUser:   BigInt!
  minerStakedUser:        Int!
  MinerTxCounterUser:     Int!
  stakeCounterUser:       Int!
  unstakeCounterUser:     Int!
  rewardClaimCounter:     Int!
}

type StakeTransaction3 @entity {
  id:                     ID!
  user:                   String!
  type:                   String!
  timeStamp:              BigInt!
  idTransaction:          BigInt!
  amountTransaction:      BigInt!
  totalStakes:            BigInt!
  totalRewardStakes:      BigInt!
  totalNormalStakes:      BigInt!
  totalBoostStakes:       BigInt!
  minerStakedChange:      Int!
  totalStakesUser:        BigInt!
  totalRewardStakesUser:  BigInt!
  totalNormalStakesUser:  BigInt!
  totalBoostStakesUser:   BigInt!
}

type GreenPowerInfo @entity {
  id:                     ID!
  counterTx:              Int!
  counterUser:            Int!
  counterMiner:           Int!
  counterOffsetTx:        Int!
  counterOffsetBatchTx:   Int!
  counterOffsetAction:    Int!
  counterStakeTx:         Int!
  counterUnstakeTx:       Int!
  counterRewardTx:        Int!
  allOffsetAmount:        BigInt!
  allStakeAmount:         BigInt!
  allStakeSum:            BigInt!
  allUnstakeSum:          BigInt!
  allRewardAmount:        BigInt!  
}

type GreenPowerUser @entity {
  id:                     ID!
  offsetTxCounter:        Int!
  offsetActionCounter:    Int!
  stakeTxCounter:         Int!
  unstakeTxCounter:       Int!
  rewardTxCounter:        Int!
  allOffsetAmount:        BigInt!
  allStakeAmount:         BigInt!
  allStakeSum:            BigInt!
  allUnstakeSum:          BigInt!
  allRewardAmount:        BigInt!
  nonce:                  Int!
}

type GreenPowerMiner @entity {
  id:                     ID!
  offsetTxCounter:        Int!
  stakeTxCounter:         Int!
  unstakeTxCounter:       Int!
  allOffsetAmount:        BigInt!
  allStakeAmount:         BigInt!
  allStakeSum:            BigInt!
  allUnstakeSum:          BigInt!
}

type GreenPowerTx @entity {
  id:                     ID!
  blockHash:              String!
  typeTx:                 String!
  txid:                   String!
  txSN:                   Int!
  greener:                String!
  minerPower:             String!
  token:                  String!
  amount:                 BigInt!
  offsetBaseIndex:        BigInt!
  timestampTx:            Int!
  period:                 Int!
  nonce:                  Int!
}

type GreenBTC20 @entity {
  id:                     ID!
  lastBlockHeight:        Int! 
  domainCount:            Int!
  actionCount:            Int!
}

type GreenBTC20Domain @entity {
  id:                   ID!
  lastBlockHeight:      Int! 
  x:                    Int!
  y:                    Int!
  w:                    Int!
  h:                    Int!
  decimal:              Int!
  boxLimit:             Int!
  boxSteps:             Int!
  chances:              [Int]!
  chanceSums:           [Int]!
  wons:                 [Int]!
  userCount:            Int!
  actionCount:          Int!
}

type GreenBT20User @entity {
  id:                   ID!
  lastBlockHeight:      Int! 
  actionCount:          Int!
  boxAmount:            Int!
}

type GreenBT20Action @entity {
  id:                   ID!
  blockHeight:          Int! 
  blockHash:            String!
  greener:              String!
  actionId:             Int!
  domainId:             Int!
  boxStart:             Int!
  boxCount:             Int!
  luckyCounter:         [Int]!  
  wonList:              [Int]!
}
